apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: contacttoamit00@gmail.com
    privateKeySecretRef:
      name: letsencrypt-secret
    solvers:
    - dns01:
        cloudflare:
          email: contacttoamit00@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: apiKey
    - http01:
        ingress:
          class: nginx

