grafana:
  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-issuer
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - grafana.0xamit.com
    tls:
      - secretName: 0xamit-com-tls
        hosts:
          - grafana.0xamit.com

prometheus:
  additionalServiceMonitors:
  - name: "ingress-nginx-monitor"
    selector:
      matchLabels:
        app.kubernetes.io/name: ingress-nginx
    namespaceSelector:
      matchNames:
        - ingress-nginx
    endpoints:
      - port: "metrics"
