defaultDashboardsEnabled: false
grafana:
  sidecar:
    dashboards:
      folderAnnotation: grafana_folder
  grafana.ini:
    server:
      root_url: https://grafana.0xamit.com
    security:
      login_maximum_inactive_lifetime_days: 30
      login_maximum_lifetime_days: 30
      token_rotation_interval_minutes: 1440
    session:
      cookie_secure: true
  admin:
    existingSecret: "grafana-admin-credentials"
    userKey: admin-user
    passwordKey: admin-password
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-issuer
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - grafana.0xamit.com
    tls:
      - secretName: 0xamit-com-tls
        hosts:
          - grafana.0xamit.com

prometheus:
  prometheusSpec:
    retention: 10d
    retentionSize: "5GB"
  additionalServiceMonitors:
  - name: "ingress-nginx-monitor"
    selector:
      matchLabels:
        app.kubernetes.io/name: ingress-nginx
    namespaceSelector:
      matchNames:
        - ingress-nginx
    endpoints:
      - port: "metrics"
