apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgutil-pot
  namespace: yt-dlp
  labels:
    app: bgutil-pot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgutil-pot
  template:
    metadata:
      labels:
        app: bgutil-pot
    spec:
      containers:
      - name: bgutil-pot
        image: brainicism/bgutil-ytdlp-pot-provider:latest
        env:
        - name: HTTP_PROXY
          value: "http://127.0.0.1:1080"
        - name: HTTPS_PROXY
          value: "http://127.0.0.1:1080"
        - name: NO_PROXY
          value: "localhost,127.0.0.1"
        ports:
        - containerPort: 4416
        resources:
          limits:
            memory: 128Mi
            cpu: 200m
          requests:
            memory: 64Mi
            cpu: 100m
        readinessProbe:
          tcpSocket:
            port: 4416
          initialDelaySeconds: 5
          periodSeconds: 10
      - name: warp
        image: caomingjun/warp:latest
        ports:
        - containerPort: 1080
---
apiVersion: v1
kind: Service
metadata:
  name: bgutil-pot-svc
  namespace: yt-dlp
spec:
  selector:
    app: bgutil-pot
  ports:
    - port: 4416
      targetPort: 4416
  type: ClusterIP
