apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yt-dlp-assets-pvc
  namespace: yt-dlp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
