apiVersion: apps/v1
kind: Deployment
metadata:
  name: yt-dlp-worker
  namespace: yt-dlp
  labels:
    app: yt-dlp-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yt-dlp-worker
  template:
    metadata:
      labels:
        app: yt-dlp-worker
    spec:
      
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: worker
        imagePullPolicy: Always
        image: ghcr.io/aimamit/yt-dlp-server:latest
        command: ["tini", "--", "celery", "-A", "app.core.celery_app:celery_app", "worker", "-Q", "downloads", "--loglevel=info"]
        env:
        - name: REDIS_URL
          value: "redis://redis:6379/0"
        - name: POT_PROVIDER_URL
          value: "http://bgutil-pot-svc:4416"
        - name: ASSETS_DIR
          value: "/assets"
        - name: HTTP_PROXY
          value: "http://127.0.0.1:8118"
        - name: HTTPS_PROXY
          value: "http://127.0.0.1:8118"
        - name: NO_PROXY
          value: "localhost,127.0.0.1,bgutil-pot-svc,redis,yt-dlp-api-svc"
        resources:
          limits:
            memory: 1Gi
            cpu: 1000m
          requests:
            memory: 512Mi
            cpu: 500m
        volumeMounts:
        - name: assets-storage
          mountPath: /assets
      - name: tor
        image: alpine:3.18
        command: ["sh", "-c", "apk add tor && echo 'SocksPort 0.0.0.0:9050' > /etc/tor/torrc && tor -f /etc/tor/torrc"]
        ports:
        - containerPort: 9050
      - name: privoxy
        image: alpine:3.18
        command: ["sh", "-c", "apk add privoxy && echo -e 'listen-address 0.0.0.0:8118\\nforward-socks5t / 127.0.0.1:9050 .' > /custom.conf && privoxy --no-daemon /custom.conf"]
        ports:
        - containerPort: 8118
      volumes:
      - name: assets-storage
        persistentVolumeClaim:
          claimName: yt-dlp-assets-pvc
