apiVersion: apps/v1
kind: Deployment
metadata:
  name: yt-dlp-worker
  namespace: yt-dlp
  labels:
    app: yt-dlp-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yt-dlp-worker
  template:
    metadata:
      labels:
        app: yt-dlp-worker
    spec:
      
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: worker
        imagePullPolicy: Always
        image: ghcr.io/aimamit/yt-dlp-server:15cadd235b04eea331c034523f288d34f63f2353
        command: ["tini", "--", "celery", "-A", "app.core.celery_app:celery_app", "worker", "-Q", "downloads", "--loglevel=info"]
        env:
        - name: REDIS_URL
          value: "redis://redis:6379/0"

        - name: ASSETS_DIR
          value: "/assets"
        - name: HTTP_PROXY
          value: "socks5h://warp-proxy-svc.warp-proxy.svc.cluster.local:1080"
        - name: HTTPS_PROXY
          value: "socks5h://warp-proxy-svc.warp-proxy.svc.cluster.local:1080"
        - name: NO_PROXY
          value: "localhost,127.0.0.1,redis,yt-dlp-api-svc"
        resources:
          limits:
            memory: 1Gi
            cpu: 1000m
          requests:
            memory: 512Mi
            cpu: 500m
        volumeMounts:
        - name: assets-storage
          mountPath: /assets

      volumes:
      - name: assets-storage
        persistentVolumeClaim:
          claimName: yt-dlp-assets-pvc
