{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "adguardhome.fullname" . }}-work
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: "keep"
{{- with .Values.persistence.annotations  }}
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    {{- include "adguardhome.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "adguardhome.fullname" . }}-conf
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: "keep"
{{- with .Values.persistence.annotations  }}
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    {{- include "adguardhome.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
