apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguardhome.fullname" . }}
  labels:
    {{- include "adguardhome.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.externalIPs }}
  externalIPs:
  {{- range . }}
    - {{ . }}
  {{- end }}
  {{- end }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ports }}
  ports:
  {{- range . }}
    - port: {{ .containerPort }}
      targetPort: {{ .containerPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "adguardhome.selectorLabels" . | nindent 4 }}
