#helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
#  --namespace ingress-nginx \
#    --create-namespace \
#      -f ingress/nginx-metal-values.yaml
#

controller:
  allowSnippetAnnotations: true
  hostNetwork: true
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"

