apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: icon-generator-embedding
  namespace: argocd
spec:
  project: default
  destination:
    namespace: icon-generator
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/AimAmit/infra.git
    targetRevision: HEAD
    path: projects/icon-generator--embedding
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
