apiVersion: v1
kind: Service
metadata:
  name: mac-ssh
  namespace: hermes
  annotations:
    tailscale.com/tailnet-fqdn: "ashmit-kumars-macbook-pro.tail94c55.ts.net"
spec:
  type: ExternalName
  externalName: placeholder
